services:
    flask:
        build:
            context: .
            dockerfile: Dockerfile
        image: fi-flask
        restart: always
        ports:
          - 5000:5000
        env_file: .env
        working_dir: /opt/fi/flask
        command: python app.py 5000
        healthcheck:
            test: curl -f http://localhost:5000/ping || exit 1
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        volumes:
            - type: volume
              source: mynfs
              target: /mnt/hd1/data
volumes:
  mynfs:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.68.147,rw" # adjust the ip address
      device: ":/mnt/hd1/data" # makesure on your nfs already have this folder