apiVersion: apps/v1
kind: Deployment
metadata:
metadata:
  namespace: gg
  name: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - name: adminer
        image: adminer
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: web
          protocol: TCP
        volumeMounts:
        - name: lg-storage
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: lg-storage
          persistentVolumeClaim:
            claimName: db-longhorn-pvc