apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: gg
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10240Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/ssd2tb/pgmount"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gg
  name: task-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1000Gi