apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gg
  name: sm-longhorn-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 40Gi