apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gg
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: disktype
                operator: In
                values:
                - ssd
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: postgres
        image: docker.io/pangyuteng/private:fi-postgres-edge
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "6"
            memory: "20Gi"
          requests:
            cpu: "4.2"
            memory: "20Gi"
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: TS_TUNE_MAX_CONNS
          value: "3000"
        ports:
        - containerPort: 5432
          name: web
          protocol: TCP
        volumeMounts:
        - name: task-pv-storage
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: task-pv-claim