apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gg
  name: luigi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: luigi
  template:
    metadata:
      labels:
        app: luigi
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: luigi
        image: docker.io/pangyuteng/private:fi-flask-edge
        imagePullPolicy: Always
        command: ["luigid"]
        ports:
        - containerPort: 8082
          name: web
          protocol: TCP
