apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gg
  name: beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: beat
        image: docker.io/pangyuteng/private:fi-flask-edge
        imagePullPolicy: Always
        command: ["bash"]
        args: ["beat.sh"]
        env:
        - name: CACHE_FOLDER
          value: /mnt/sm-data/fi
        - name: AMQP_URI
          value: amqp://rabbitmq:5672
        - name: REDIS_URI
          value: redis://redis:6379/1
        - name: POSTGRES_URI
          value: postgres://postgres:postgres@postgres:5432/postgres
        - name: C_FORCE_ROOT
          value: "true"
        - name: TELEGRAM_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: tasty-env
              key: TELEGRAM_BOT_TOKEN
        volumeMounts:
        - name: sm-volume
          mountPath: /mnt/sm-data
        # used below lg-storage to manage db data, if need to nuke, need to first shutdown postgres.
        - name: lg-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: sm-volume
        persistentVolumeClaim:
          claimName: sm-longhorn-pvc
      - name: lg-storage
        persistentVolumeClaim:
          claimName: db-longhorn-pvc