apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gg
  name: beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beat
  template:
    metadata:
      labels:
        app: beat
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: beat
        image: docker.io/pangyuteng/private:fi-flask-edge
        imagePullPolicy: Always
        command: ["bash"]
        args: ["beat.sh"]
        env:
        - name: CACHE_FOLDER
          value: /mnt/hd1/data/fi
        - name: CACHE_TASTY_FOLDER
          value: /mnt/hd1/data/tastyfi
        - name: AMQP_URI
          value: amqp://rabbitmq:5672
        - name: REDIS_URI
          value: redis://redis:6379/1
        - name: POSTGRES_URI
          value: postgres://postgres:postgres@postgres:5432/postgres
        - name: C_FORCE_ROOT
          value: "true"
        volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/hd1/data
      volumes:
      - name: nfs-volume
        nfs:
          server: 192.168.68.141
          path: /mnt/hd1/data
