apiVersion: apps/v1
kind: Deployment
metadata:
  name: fi-postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fi-postgres
  template:
    metadata:
      labels:
        app: fi-postgres
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: web
        image: docker.io/pangyuteng/private:fi-postgres-edge
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: web
          protocol: TCP
        volumeMounts:
        - name: nfs-volume
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      volumes:
      - name: nfs-volume
        nfs:
          server: 192.168.68.147
          path: /mnt/hd1/data
