apiVersion: v1
kind: Service
metadata:
  name: fi-adminer
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  selector:
    app: fi-adminer
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
