apiVersion: v1
kind: Service
metadata:
  name: fi-postgres
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  selector:
    app: fi-postgres
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
