apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gg
  name: flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: web
        image: docker.io/pangyuteng/private:fi-flask-edge
        imagePullPolicy: Always
        env:
        - name: CACHE_FOLDER
          value: /mnt/hd1/data/fi
        - name: CACHE_TASTY_FOLDER
          value: /mnt/hd1/data/tastyfi
        - name: AMQP_URI
          value: amqp://rabbitmq:5672
        - name: REDIS_URI
          value: redis://redis:6379/1
        - name: POSTGRES_URI
          value: postgres://postgres:postgres@postgres:5432/postgres
        command: ["python"]
        args: ["app.py", "80"]
        ports:
        - containerPort: 80
          name: web
          protocol: TCP
        volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/hd1/data
      volumes:
      - name: nfs-volume
        nfs:
          server: 192.168.68.141
          path: /mnt/hd1/data