kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-gg
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "1"
  fromBackup: ""
  fsType: "ext4"
  nodeSelector: "storage,fast"
  diskSelector: "ssd"
