apiVersion: apps/v1
kind: Deployment
metadata:
  name: fi-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fi-app
  template:
    metadata:
      labels:
        app: fi-app
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: web
        image: docker.io/pangyuteng/private:main
        imagePullPolicy: Always
        env:
        - name: OK
          value: HAHA
        command: ["python"]
        args: ["qapp.py", "80"]
        ports:
        - containerPort: 80
          name: web
          protocol: TCP