apiVersion: apps/v1
kind: Deployment
metadata:
  name: fi-app
  labels:
    k8s-app: fi-app
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: fi-app
  template:
    metadata:
      labels:
        k8s-app: fi-app
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
      - name: web
        image: docker.io/pangyuteng/private:fi-aigonewrong-main
        imagePullPolicy: Always
        env:
        - name: OK
          value: HAHA
        command: ["python"]
        args: ["qapp.py", "5000"]
        ports:
        - containerPort: 5000
          name: web
          protocol: TCP