apiVersion: v1
kind: Service
metadata:
  name: fi-app
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    k8s-app: fi-app
  type: LoadBalancer