apiVersion: v1
kind: Service
metadata:
  name: fi-app
  # annotations:
  #   metallb.universe.tf/address-pool: first-pool
spec:
  selector:
    app: fi-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
